// SPDX-License-Identifier: GPL-3.0-or-later
// elads — save an edited MapModel back into an archive (GUI/GL-free).
//
// Serializes the model into a map's lumps — the 5 editable Doom lumps (binary) or a single
// TEXTMAP (+ENDMAP) for UDMF — and splices them into a Wad in place, replacing the map's
// existing data lumps while preserving the marker and every non-map lump. Stale build lumps
// (NODES/BLOCKMAP/…) inside the map are dropped, to be regenerated by the node builder. See
// docs/design/07-build-test-pipeline.md and the B4 plan item.
#pragma once

#include <string>

#include "archive/wad.h"
#include "mapeditor/model/map_model.h"

namespace elads::map {

// Load a map from a WAD by name (binary or UDMF). Throws std::runtime_error if not present.
MapModel loadMapFromWad(const archive::Wad&, const std::string& mapName);

// Write `model` into `wad` as `mapName`. If the map exists its data lumps are replaced in place;
// otherwise a new map (marker + data lumps) is appended. `udmf` selects TEXTMAP output using
// `namespaceId`; otherwise the classic binary lumps are written. Non-map lumps are untouched.
void saveMapToWad(archive::Wad& wad, const std::string& mapName, const MapModel& model,
                  bool udmf = false, const std::string& namespaceId = "zdoom");

} // namespace elads::map
